/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Alpha */

#ifndef _Included_Alpha
#define _Included_Alpha
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Alpha
 * Method:    cifrar
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Alpha_cifrar
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jint, jint);

/*
 * Class:     Alpha
 * Method:    decifrar
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Alpha_decifrar
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jint, jint);

/*
 * Class:     Alpha
 * Method:    setIterations
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Alpha_setIterations
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
