/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class main_Alpha */

#ifndef _Included_main_Alpha
#define _Included_main_Alpha
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     main_Alpha
 * Method:    decifrar
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_main_Alpha_decifrar
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jint, jint);

/*
 * Class:     main_Alpha
 * Method:    cifrar
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_main_Alpha_cifrar
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
